-- Category
INSERT INTO CATEGORY (id, version, name) VALUES (1, 1, 'Arts & Photography')
INSERT INTO CATEGORY (id, version, name) VALUES (2, 1, 'Biographies & Memoirs')
INSERT INTO CATEGORY (id, version, name) VALUES (3, 1, 'Business & Money')
INSERT INTO CATEGORY (id, version, name) VALUES (4, 1, 'Comics & Graphic Novels')
INSERT INTO CATEGORY (id, version, name) VALUES (5, 1, 'Computers & Technology')
INSERT INTO CATEGORY (id, version, name) VALUES (6, 1, 'Cookbooks, Food & Wine')
INSERT INTO CATEGORY (id, version, name) VALUES (7, 1, 'Engineering & Transportation')
INSERT INTO CATEGORY (id, version, name) VALUES (8, 1, 'Health, Fitness & Dieting')
INSERT INTO CATEGORY (id, version, name) VALUES (9, 1, 'Literature & Fiction')
INSERT INTO CATEGORY (id, version, name) VALUES (10, 1, 'Mystery, Thriller & Suspense')
INSERT INTO CATEGORY (id, version, name) VALUES (11, 1, 'Science & Math')
INSERT INTO CATEGORY (id, version, name) VALUES (12, 1, 'Science Fiction & Fantasy')

-- Category
INSERT INTO GENRE (id, version, name) VALUES (1, 1, 'Alternative Rock')
INSERT INTO GENRE (id, version, name) VALUES (2, 1, 'Blues')
INSERT INTO GENRE (id, version, name) VALUES (3, 1, 'Classical Music')
INSERT INTO GENRE (id, version, name) VALUES (4, 1, 'Classic Rock')
INSERT INTO GENRE (id, version, name) VALUES (5, 1, 'Country')
INSERT INTO GENRE (id, version, name) VALUES (6, 1, 'Indie Music')
INSERT INTO GENRE (id, version, name) VALUES (7, 1, 'Jazz')
INSERT INTO GENRE (id, version, name) VALUES (8, 1, 'Latin Music')
INSERT INTO GENRE (id, version, name) VALUES (9, 1, 'Pop')
INSERT INTO GENRE (id, version, name) VALUES (10, 1, 'R&B')
INSERT INTO GENRE (id, version, name) VALUES (11, 1, 'Reggae')
INSERT INTO GENRE (id, version, name) VALUES (12, 1, 'Rock')
INSERT INTO GENRE (id, version, name) VALUES (13, 1, 'Soundtracks')
INSERT INTO GENRE (id, version, name) VALUES (14, 1, 'World Music')

-- MajorLabel
INSERT INTO MAJORLABEL (id, version, name) VALUES (1, 1, 'Warner Music Group')
INSERT INTO MAJORLABEL (id, version, name) VALUES (2, 1, 'EMI')
INSERT INTO MAJORLABEL (id, version, name) VALUES (3, 1, 'Sony')
INSERT INTO MAJORLABEL (id, version, name) VALUES (4, 1, 'BMG')
INSERT INTO MAJORLABEL (id, version, name) VALUES (5, 1, 'Universal Music Group')
INSERT INTO MAJORLABEL (id, version, name) VALUES (6, 1, 'PolyGram')

-- Publisher
INSERT INTO PUBLISHER (id, version, name) VALUES (1, 1, 'Pearson')
INSERT INTO PUBLISHER (id, version, name) VALUES (2, 1, 'Hachette Livre')
INSERT INTO PUBLISHER (id, version, name) VALUES (3, 1, 'Wiley')
INSERT INTO PUBLISHER (id, version, name) VALUES (4, 1, 'Oxford University Press')
INSERT INTO PUBLISHER (id, version, name) VALUES (5, 1, 'Harlequin')
INSERT INTO PUBLISHER (id, version, name) VALUES (6, 1, 'Flammarion')
INSERT INTO PUBLISHER (id, version, name) VALUES (7, 1, 'Groupe Gallimard')
INSERT INTO PUBLISHER (id, version, name) VALUES (8, 1, 'APress')
