drop table Author if exists
drop table Book if exists
drop table CD if exists
drop table CD_Musician if exists
drop table Category if exists
drop table Customer if exists
drop table Genre if exists
drop table Item if exists
drop table MajorLabel if exists
drop table Musician if exists
drop table OrderLine if exists
drop table Publisher if exists
drop table PurchaseOrder if exists
drop table PurchaseOrder_OrderLine if exists
